### ISSUE TITLE
Form is not showing in checkout Step "Customer Login"

### ISSUE THREAD

**Issue by rishigupta121** [graschik/magento-2-checkout-login-step#1]
I am using magento 2.4.6-p2 . step is created but form is not loading. show like in this image

![image](https://github.com/graschik/magento-2-checkout-login-step/assets/10168273/b6ea6a0f-a7c4-43a3-b77c-b37469090b51)

**Comment by graschik** [comment]
Fixed. Install version 5.0.0 of this module
